//===----------------------------------------------------------------------===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

// UNSUPPORTED: c++03 || c++11 || c++14 || c++17 || c++20
// ADDITIONAL_COMPILE_FLAGS: -freflection
// ADDITIONAL_COMPILE_FLAGS: -ftoken-injection
// ADDITIONAL_COMPILE_FLAGS: -fparameter-reflection
// ADDITIONAL_COMPILE_FLAGS: -Wno-unused-private-field

// <experimental/reflection>
//
// [reflection]
//
// RUN: %{exec} %t.exe > %t.stdout
//
// A tour of token sequence injection (P3294): token sequences '^^{ ... }',
// their interpolators, consteval blocks, 'queue_injection',
// 'namespace_inject' and 'list_builder'.
//
// Interpolators within '^^{ ... }':
//   \[ "a"sv, x, 1 ]  - an identifier made of strings and integers
//   \[: r :]          - a splice of a reflection
//   \{ tokens }       - the tokens of another token sequence
//   \val( expr )      - the value of an expression, as a literal
//   \str( sv )        - a string literal

#include <meta>

#include <cassert>
#include <cstdio>
#include <initializer_list>
#include <string>
#include <string_view>
#include <vector>

using namespace std::meta;
using namespace std::string_view_literals;

consteval std::vector<info> fields_of(info type) {
  return nonstatic_data_members_of(type, access_context::unchecked());
}

                    // ====================================
                    // namespace_scope_constants_and_functions
                    // ====================================

consteval void make_powers(int count) {
  for (int i = 0; i < count; ++i) {
    queue_injection(^^{ constexpr long \["pow2_"sv, i] = \val(1L << i); });
  }
}
consteval { make_powers(5); }  // pow2_0 ... pow2_4

static_assert(pow2_0 == 1 && pow2_1 == 2 && pow2_2 == 4 && pow2_3 == 8 &&
              pow2_4 == 16);

// A function of n parameters: both the parameter list and the body are
// assembled from pieces.
consteval info make_sum(std::string_view name, int n) {
  list_builder params;                // the default separator is ','
  list_builder terms(^^{ + });
  for (int i = 0; i < n; ++i) {
    params += ^^{ long \["a"sv, i] };
    terms  += ^^{ \["a"sv, i] };
  }
  return ^^{ constexpr long \[name](\{params}) { return \{terms}; } };
}
consteval { queue_injection(make_sum("sum4", 4)); }

static_assert(sum4(1, 2, 3, 4) == 10);

// 'namespace_inject' adds declarations to the nearest enclosing namespace.
namespace app {
consteval {
  namespace_inject(^^{
    constexpr const char* build_info = \str("generated by token injection"sv);
  });
}
}  // namespace app

static_assert(std::string_view(app::build_info) ==
              "generated by token injection");

                          // ========================
                          // generated_enumeration
                          // ========================

consteval void make_enum(std::string_view name,
                         std::initializer_list<std::string_view> values) {
  list_builder items;
  for (std::string_view v : values) items += ^^{ \[v] };
  queue_injection(^^{ enum class \[name] { \{items} }; });
}
consteval { make_enum("Fruit", {"apple", "banana", "cherry"}); }

static_assert(enumerators_of(^^Fruit).size() == 3);
static_assert(identifier_of(enumerators_of(^^Fruit)[1]) == "banana");
static_assert(static_cast<int>(Fruit::cherry) == 2);

                        // ============================
                        // class_members_as_properties
                        // ============================

consteval void property(info type, std::string_view name) {
  queue_injection(^^{
    private:
      \[:type:] \["m_"sv, name]{};
    public:
      \[:type:] \["get_"sv, name]() const { return \["m_"sv, name]; }
      void \["set_"sv, name](\[:type:] value) { \["m_"sv, name] = value; }
  });
}

class Person {
  consteval {
    property(^^std::string, "name");
    property(^^int, "age");
  }
};

                    // ===================================
                    // new_class_from_members_of_another
                    // ===================================

struct Point {
  int x;
  int y;
};

// A "tracking" wrapper, which counts the writes to each of its fields.
consteval void make_tracked(info source, std::string_view name) {
  list_builder members(^^{});         // no separator
  for (info m : fields_of(source)) {
    std::string_view f = identifier_of(m);
    members += ^^{
      \[:type_of(m):] \[f]{};
      int \[f, "_writes"sv] = 0;
      void \["set_"sv, f](\[:type_of(m):] value) {
        \[f] = value;
        ++\[f, "_writes"sv];
      }
    };
  }
  queue_injection(^^{ struct \[name] { \{members} }; });
}
consteval { make_tracked(^^Point, "TrackedPoint"); }

static_assert(nonstatic_data_members_of(
                  ^^TrackedPoint, access_context::unchecked()).size() == 4);

                            // ====================
                            // dispatcher_by_name
                            // ====================

struct Commands {
  int start()  { return 1; }
  int stop()   { return 2; }
  int status() { return 3; }
};

// A chain of 'if' statements over every member function without parameters.
consteval void make_dispatcher(info cls) {
  info body = ^^{};
  for (info m : members_of(cls, access_context::unchecked())) {
    if (is_function(m) && !is_special_member_function(m) &&
        parameters_of(m).empty()) {
      body = ^^{
        \{body}
        if (name == \str(identifier_of(m))) return obj.\[:m:]();
      };
    }
  }
  queue_injection(^^{
    int dispatch(typename \[:cls:]& obj, std::string_view name) {
      \{body}
      return -1;
    }
  });
}
consteval { make_dispatcher(^^Commands); }

int main() {
  // Namespace-scope constants and functions.
  assert(pow2_0 + pow2_1 + pow2_2 + pow2_3 + pow2_4 == 31);
  assert(sum4(1, 2, 3, 4) == 10);
  std::printf("app::build_info = %s\n", app::build_info);

  // Generated enumeration.
  assert(static_cast<int>(Fruit::apple) == 0);
  assert(static_cast<int>(Fruit::banana) == 1);

  // Class members.
  Person p;
  p.set_name("Grace");
  p.set_age(85);
  assert(p.get_name() == "Grace");
  assert(p.get_age() == 85);

  // Class generated from the members of 'Point'.
  TrackedPoint t;
  t.set_x(1);
  t.set_x(2);
  t.set_y(5);
  assert(t.x == 2 && t.x_writes == 2);
  assert(t.y == 5 && t.y_writes == 1);

  // Dispatcher.
  Commands cmds;
  assert(dispatch(cmds, "start") == 1);
  assert(dispatch(cmds, "status") == 3);
  assert(dispatch(cmds, "reboot") == -1);
  assert(dispatch(cmds, "stop") == 2);
}
